name: CD

on:
  push:
    tags:
      - 'v*'

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{github.token}}
        with:
          tag_name: ${{github.ref}}
          release_name: ${{github.ref}}
