name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2

      - name: Install deps
        run: sudo apt install -y libgtk-3-dev libxml2-utils meson gettext

      - name: Cache build
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-build-${{ hashFiles('**/*.go') }}
          restore-keys: ${{ runner.os }}-go-build

      - name: Build project
        run: meson build && ninja -C build

      - name: Install software
        run: sudo meson install -C build --no-rebuild

      - name: Run program
        run: checksumo --help

      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          path: build/src/checksumo
