name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  code:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Install deps
        run: |
          if test "$RUNNER_OS" = "Linux"; then
            sudo apt install -y libgtk-3-dev
          else
            brew install gtk+3
          fi
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: ~/.cache/go-build
          key: ${{runner.os}}-go-build-${{hashFiles('**/*.go')}}
          restore-keys: ${{runner.os}}-go-build
      - name: Build project
        run: make
      - name: Test code
        run: make test
      - name: Install software
        run: sudo make install
      - name: Run program
        run: checksumo --help
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Cache build
        uses: actions/cache@v2
        with:
          path: debian/go-build
          key: ${{runner.os}}-go-build-${{hashFiles('**/*.go')}}
          restore-keys: ${{runner.os}}-go-build
      - name: Build package
        uses: dawidd6/action-debian-package@v1
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          path: '*.deb'
